# Generated by Django 2.2.4 on 2019-08-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=5, null=True)),
                ('preco', models.FloatField()),
                ('tipo', models.CharField(max_length=1)),
            ],
        ),
    ]
