# Generated by Django 2.2.4 on 2019-08-10 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='token',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10000000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=15),
        ),
    ]
