# Generated by Django 2.2.4 on 2019-08-10 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_auto_20190810_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10000000000), django.core.validators.MinValueValidator]),
        ),
    ]
