# Generated by Django 2.2.4 on 2019-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_auto_20190811_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
